Repository elrouss/spanish-with-anna, pull requests merged in 2023-06, with the labels that each got.

#44 Feat/header
  frontend/src/assets/icons/logo.jsx
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/header.module.scss
  frontend/src/pages/index.jsx
  frontend/src/styles/abstracts/placeholders.scss
Labels: enhancement

#48 Feat/facts
  frontend/src/components/Facts/Fact.jsx
  frontend/src/components/Facts/Facts.jsx
  frontend/src/components/Facts/Facts.module.scss
  frontend/src/pages/index.jsx
  frontend/src/styles/abstracts/variables/fonts.scss
  frontend/src/utils/data/facts.jsx
Labels: enhancement

#47 Feat/intro
  frontend/src/assets/icons/intro-heading.jsx
  frontend/src/assets/images/intro-heading.svg
  frontend/src/components/Intro/Intro.jsx
  frontend/src/components/Intro/Intro.module.scss
  frontend/src/pages/index.jsx
Labels: enhancement

#50 Feat/info
  frontend/public/assets/images/intro-heading.svg
  frontend/public/assets/images/intro-image-course-registration.png
  frontend/public/assets/images/intro-image-main.png
  frontend/public/assets/images/online-courses-info-1.jpg
  frontend/public/assets/images/online-courses-info-2.jpg
  frontend/public/assets/images/online-courses-info-3.jpg
  frontend/public/assets/images/review-larisa.jpg
  frontend/public/assets/images/review-mary.jpg
  frontend/public/assets/images/translation-book.jpg
  frontend/src/components/Info/Info.jsx
  frontend/src/components/Info/Info.module.scss
  frontend/src/components/Info/InfoCard.jsx
  frontend/src/pages/index.jsx
  frontend/src/utils/data/INFO_CARDS.jsx
Labels: enhancement

#51 feat: mark up section benefits on desktop Closes #32
  frontend/public/assets/icons/book.svg
  frontend/public/assets/icons/box.svg
  frontend/public/assets/icons/maracas.svg
  frontend/public/assets/icons/microphone.svg
  frontend/public/assets/icons/smiling-face.svg
  frontend/public/assets/icons/star.svg
  frontend/public/assets/icons/tile-1.svg
  frontend/public/assets/icons/tile-2.svg
  frontend/src/assets/icons/book.jsx
  frontend/src/assets/icons/box.jsx
  frontend/src/assets/icons/maracas.jsx
  frontend/src/assets/icons/microphone.jsx
  frontend/src/assets/icons/smiling-face.jsx
  frontend/src/assets/icons/star.jsx
  frontend/src/components/StudyingBenefits/StudyingBenefit/StudyingBenefit.jsx
  frontend/src/components/StudyingBenefits/StudyingBenefit/StudyingBenefit.module.scss
  frontend/src/components/StudyingBenefits/StudyingBenefits.jsx
  frontend/src/components/StudyingBenefits/StudyingBenefits.module.scss
  frontend/src/pages/index.jsx
  frontend/src/utils/data/studyingBenefits.jsx
Labels: enhancement

#43 feat: add footer
  frontend/src/assets/icons/telegram.jsx
  frontend/src/assets/icons/youtube.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/FooterLink/FooterLink.jsx
  frontend/src/components/Footer/FooterLink/FooterLink.module.scss
  frontend/src/components/Footer/footer.module.scss
  frontend/src/pages/_app.jsx
  frontend/src/pages/index.jsx
  frontend/src/styles/abstracts/variables/colors.scss
  frontend/src/styles/components/icons.scss
  frontend/src/styles/index.scss
Labels: enhancement

#61 Feat/frontend layout desktop reviews
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/icons/arrow-left.svg
  frontend/public/assets/icons/arrow-right.svg
  frontend/public/assets/icons/close-icon.svg
  frontend/public/assets/images/review-angelina.webp
  frontend/public/assets/images/review-brad.webp
  frontend/public/assets/images/review-christine.jpeg
  frontend/public/assets/images/review-hugh.webp
  frontend/public/assets/images/review-justin.webp
  frontend/public/assets/images/review-kate.jpeg
  frontend/public/assets/images/review-kim.jpeg
  frontend/public/assets/images/review-leonardo.webp
  frontend/public/assets/images/review-natalia.jpg
  frontend/public/assets/images/review-richard.jpeg
  frontend/public/assets/images/review-rikki.jpeg
  frontend/public/assets/images/review-sarah.jpg
  frontend/public/assets/images/review-synthia.jpeg
  frontend/public/favicon.ico
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/src/assets/fonts/fonts.jsx
  frontend/src/assets/icons/arrow-left.jsx
  frontend/src/assets/icons/arrow-right.jsx
  frontend/src/assets/images/review-larisa.jpg
  frontend/src/assets/images/review-mary.jpg
  frontend/src/components/ModalOverlay/ModalOverlay.jsx
  frontend/src/components/ModalOverlay/ModalOverlay.module.scss
  frontend/src/components/Reviews/CarouselButton/CarouselButton.jsx
  frontend/src/components/Reviews/CarouselButton/CarouselButton.module.scss
  frontend/src/components/Reviews/Review/Review.jsx
  frontend/src/components/Reviews/Review/Review.module.scss
  frontend/src/components/Reviews/ReviewDetails/ReviewDetails.jsx
  frontend/src/components/Reviews/ReviewDetails/ReviewDetails.module.scss
  frontend/src/components/Reviews/Reviews.jsx
  frontend/src/components/Reviews/Reviews.module.scss
  frontend/src/hooks/.gitkeep
  frontend/src/hooks/useCloseModal.jsx
  frontend/src/pages/_app.jsx
  frontend/src/pages/_document.jsx
  frontend/src/pages/index.jsx
  frontend/src/styles/globals.scss
  frontend/src/utils/data/.gitkeep
  frontend/src/utils/data/reviews.jsx
Labels: enhancement

#58 Feat/signup section
  frontend/public/assets/icons/Ellipse.svg
  frontend/src/assets/icons/gift.jsx
  frontend/src/components/Signup/Signup.jsx
  frontend/src/components/Signup/signup.module.scss
  frontend/src/pages/index.jsx
  frontend/src/styles/abstracts/placeholders.scss
  frontend/src/styles/abstracts/variables/colors.scss
Labels: enhancement

#66 Feat/translation
  frontend/public/assets/icons/tile-4.svg
  frontend/public/assets/icons/translation.svg
  frontend/src/components/ServicesTranslation/ServicesTranslation.jsx
  frontend/src/components/ServicesTranslation/ServicesTranslation.module.scss
  frontend/src/pages/index.jsx
  frontend/src/styles/abstracts/variables/colors.scss
Labels: enhancement

#64 Feat 33/frontend layout desktop decorative background (closes #33)
  frontend/public/assets/icons/billet-1.svg
  frontend/public/assets/icons/billet-2.svg
  frontend/public/assets/icons/billet-3.svg
  frontend/public/assets/images/city.svg
  frontend/src/assets/fonts/fonts.jsx
  frontend/src/assets/icons/city.jsx
  frontend/src/components/DecorativeBackground/DecorativeBackground.jsx
  frontend/src/components/DecorativeBackground/DecorativeBackground.module.scss
  frontend/src/pages/index.jsx
Labels: enhancement

#65 fix: dropdown menu
  frontend/src/components/Header/Header.jsx
  frontend/src/components/Header/header.module.scss
Labels: refactoring

#67 Feat/faq
  frontend/public/assets/icons/arrow-down.svg
  frontend/public/assets/icons/question.svg
  frontend/public/assets/icons/tile-5.svg
  frontend/public/assets/icons/tile-6.svg
  frontend/public/assets/icons/tile-7.svg
  frontend/src/components/FAQ/FAQ.jsx
  frontend/src/components/FAQ/FAQ.module.scss
  frontend/src/components/FAQ/Question/Question.jsx
  frontend/src/components/FAQ/Question/Question.module.scss
  frontend/src/pages/index.jsx
  frontend/src/styles/abstracts/variables/colors.scss
  frontend/src/utils/data/FAQ_DATA.jsx
Labels: enhancement

#72 docs: create README
  README.md
Labels: documentation

#75 feat: describe validation errors for user and server
  frontend/src/utils/validation-messages.jsx
Labels: enhancement

#77 feat: add date_of_birth and language_level fields
  backend/spanish_with_anna/users/models.py
Labels: good first issue

#76 Fix/pp and animation
  frontend/src/components/FAQ/FAQ.module.scss
  frontend/src/components/FAQ/Question/Question.module.scss
  frontend/src/components/Facts/Facts.jsx
  frontend/src/components/Facts/Facts.module.scss
  frontend/src/utils/data/FAQ_DATA.jsx
Labels: refactoring

#78 Feat/layout desktop
  frontend/src/components/FAQ/FAQ.module.scss
  frontend/src/components/FAQ/Question/Question.module.scss
  frontend/src/components/Facts/Facts.jsx
  frontend/src/components/Facts/Facts.module.scss
  frontend/src/utils/data/FAQ_DATA.jsx
Labels: refactoring

#74 feat: add CustomField and structure to execute
  frontend/src/assets/icons/EyeOff.jsx
  frontend/src/assets/icons/EyeOn.jsx
  frontend/src/components/forms/CustomInput/CustomInput.jsx
  frontend/src/components/forms/CustomInput/CustomInput.module.scss
  frontend/src/components/forms/Login/LoginForm.jsx
  frontend/src/components/forms/Login/LoginForm.module.scss
  frontend/src/components/forms/yapSchemas/yapSchemas.js
  frontend/src/pages/signin/index.jsx
  frontend/src/styles/abstracts/variables/colors.scss
  frontend/src/utils/constants.jsx
Labels: enhancement

#82 feature: add email settings
  backend/spanish_with_anna/api/views.py
  backend/spanish_with_anna/example.env
  backend/spanish_with_anna/spanish_with_anna/settings.py
  backend/spanish_with_anna/users/managers.py
  backend/spanish_with_anna/users/models.py
Labels: enhancement
